server:
  port: 8081
  servlet:
    context-path: /dlang

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wcard
    username: vova
    password: adminvova
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
